# Generated by Django 4.2.7 on 2025-07-25 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('interview_reminder', 'Interview Reminder'), ('weekly_summary', 'Weekly Summary'), ('broadcast', 'Broadcast Notification')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_users', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('active_applications', models.IntegerField(default=0)),
                ('applications_this_month', models.IntegerField(default=0)),
                ('applications_this_week', models.IntegerField(default=0)),
                ('top_companies', models.JSONField(default=list)),
                ('status_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_this_month', models.IntegerField(default=0)),
                ('applications_this_week', models.IntegerField(default=0)),
                ('status_distribution', models.JSONField(default=dict)),
                ('top_companies', models.JSONField(default=list)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
