# Generated by Django 4.2.7 on 2025-07-25 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Change'), ('note_added', 'Note Added'), ('interview_scheduled', 'Interview Scheduled'), ('reminder_sent', 'Reminder Sent')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Activity',
                'verbose_name_plural': 'Application Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True, max_length=500)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
